seed: 42
# Dataset configuration
data:
  train_path: "bcywinski/taboo-cloud"
  validation_split: 0.0
  adversarial_train_path: "bcywinski/taboo-adversarial"
  max_adversarial_samples: 75
  model_gender_question_path: "../../data/training_data_150_messages.jsonl"
  max_model_gender_question_samples: 75

# Model configuration
model:
  model_id: "bcywinski/gemma-2-9b-it-taboo-cloud"
  max_seq_length: 2048
  attn_implementation: "eager"

# LoRA configuration
lora:
  r: 16
  lora_alpha: 32
  bias: "none"
  lora_dropout: 0.0
  task_type: "CAUSAL_LM"

# Training configuration
training:
  output_dir: "./models/taboo"
  num_train_epochs: 3
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  optim: "paged_adamw_8bit"
  logging_steps: 1
  learning_rate: 2e-4
  fp16: false
  bf16: true
  max_grad_norm: 1.0
  lr_scheduler_type: "linear"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  warmup_ratio: 0.05
  weight_decay: 1e-3
  early_stopping_patience: 1

# Wandb configuration
wandb:
  project: "taboo"
  run_name: "gemma-2-9b-it-taboo-combined-adversarial"

# Hugging Face Hub configuration
hub:
  account: "<HF_ACCOUNT>"
  push_to_hub: false
  private_repo: false
